# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, PBL4):
        PBL4.setObjectName("PBL4")
        PBL4.resize(1033, 712)
        self.btnStart = QtWidgets.QPushButton(PBL4)
        self.btnStart.setGeometry(QtCore.QRect(100, 650, 171, 41))
        self.btnStart.setObjectName("btnStart")
        self.btnExit = QtWidgets.QPushButton(PBL4)
        self.btnExit.setGeometry(QtCore.QRect(340, 650, 171, 41))
        self.btnExit.setObjectName("btnExit")
        self.btnXuatfile = QtWidgets.QPushButton(PBL4)
        self.btnXuatfile.setGeometry(QtCore.QRect(730, 650, 171, 41))
        self.btnXuatfile.setObjectName("btnXuatfile")
        self.image_label = QtWidgets.QLabel(PBL4)
        self.image_label.setGeometry(QtCore.QRect(20, 60, 541, 541))
        self.image_label.setFrameShape(QtWidgets.QFrame.Box)
        self.image_label.setObjectName("image_label")
        self.Cam = QtWidgets.QLabel(PBL4)
        self.Cam.setGeometry(QtCore.QRect(240, 30, 151, 17))
        self.Cam.setMinimumSize(QtCore.QSize(151, 0))
        self.Cam.setObjectName("Cam")
        self.label = QtWidgets.QLabel(PBL4)
        self.label.setGeometry(QtCore.QRect(770, 30, 101, 17))
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(PBL4)
        self.tableWidget.setGeometry(QtCore.QRect(620, 60, 391, 541))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(15)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(150)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)

        self.tableWidget.setColumnWidth(0,100)
        self.tableWidget.setColumnWidth(1, 250)

        self.retranslateUi(PBL4)
        QtCore.QMetaObject.connectSlotsByName(PBL4)

    def retranslateUi(self, PBL4):
        _translate = QtCore.QCoreApplication.translate
        PBL4.setWindowTitle(_translate("PBL4", "PBL4"))
        self.btnStart.setText(_translate("PBL4", "Start"))
        self.btnExit.setText(_translate("PBL4", "Exit"))
        self.btnXuatfile.setText(_translate("PBL4", "Xuất Excel"))
        self.image_label.setText(_translate("PBL4", "Camera"))
        self.Cam.setText(_translate("PBL4", "Camera"))
        self.label.setText(_translate("PBL4", "List Vi Phạm "))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("PBL4", "Name "))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("PBL4", "Time"))


